{
  imports = [
    ./adb
    ./agenix
    ./attic
    ./authentik
    ./backup
    ./basic-packages
    ./bootloader
    ./build-vm
    ./certs
    ./cheshbot
    ./cleanup
    ./cloudflare-warp
    ./collabora
    ./desktop
    ./docker
    ./fedifetcher
    ./firewall
    ./firmware-update
    ./fonts
    ./gaming
    ./gitlab
    ./grafana
    ./hardware
    ./hetzner
    ./home-manager
    ./latest-kernel
    ./locale
    ./mastodon
    ./matrix
    ./mudblazor-docs
    ./networking-tools
    ./nginx
    ./nix
    ./oci-containers
    ./openfortivpn
    ./openssh
    ./optimization
    ./overlays
    ./plasma
    ./postgresql
    ./promtail
    ./stylix
    ./users
    ./virtualbox
    ./vpn
    ./workarounds
    ./yubikey
    ./zsh
  ];
}
