{
  imports = [
    ./adb
    ./agenix
    ./attic
    ./audio
    ./auto-upgrade
    ./backup
    ./basic-packages
    ./beeper
    ./bootloader
    ./build-vm
    ./certs
    ./cheshbot
    ./cleanup
    ./cloudflare-warp
    ./collabora
    ./desktop
    ./distributed-build
    ./docker
    ./fedifetcher
    ./firmware-update
    ./fonts
    ./gaming
    ./grafana
    ./hardware
    ./hetzner
    ./home-manager
    ./hyprland
    ./latest-kernel
    ./locale
    ./mastodon
    ./matrix
    ./mudblazor-docs
    ./networking-tools
    ./nginx
    ./nix
    ./oci-containers
    ./openfortivpn
    ./openssh
    ./optimization
    ./overlays
    ./plasma
    ./plymouth
    ./postgresql
    ./printing
    ./promtail
    ./remote-desktop
    ./security
    ./server
    ./services
    ./stylix
    ./sudo-rs
    ./users
    ./verapdf
    ./virt-manager
    ./virtualbox
    ./vpn
    ./winboat
    ./workarounds
    ./yubikey
    ./zsh
  ];
}
