disabled = [
  "manual_inherit",
  "manual_inherit_from",
  "redundant_pattern_bind",
  "unquoted_uri",
  "empty_inherit",
  "deprecated_to_path",
  "bool_simplification",
  "useless_has_attr",
  "repeated_keys",
  "empty_list_concat"
]
