name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: nixos
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Nix
        run: "$SETUP_NIX_SCRIPT"
      - uses: DeterminateSystems/flake-checker-action@786422608c7bded2bbc9741ad9f91356842bf520 # main
      - name: Setup Attic cache
        uses: ryanccn/attic-action@dc99f5eb1d5c0495aa26f7b56337b30011fa153e # v0.5.2
        with:
          endpoint: https://attic.mnzn.dev
          cache: main
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Check flake
        run: nix flake check
      - name: Install direnv
        run: |
          if ! command -v direnv >/dev/null 2>&1; then
            nix profile add nixpkgs#direnv nixpkgs#nix-direnv
          else
            echo "direnv is already installed, skipping installation"
          fi
      - name: Set up direnv
        run: direnv allow
      - name: Colmena build
        run: direnv exec . colmena build --verbose --no-build-on-target
