{
  imports = [
    ./adb
    ./agenix
    ./authentik
    ./bootloader
    ./build-vm
    ./certs
    ./cleanup
    ./cloudflare-warp
    ./desktop
    ./docker
    ./fedifetcher
    ./firmware-update
    ./fonts
    ./gaming
    ./hardware
    ./hetzner
    ./home-manager
    ./hostname
    ./kernel
    ./locale
    ./mastodon
    ./matrix
    ./networking
    ./networking-tools
    ./nginx
    ./nix
    ./oci-containers
    ./openssh
    ./optimization
    ./overlays
    ./postgresql
    ./programs
    ./state-version
    ./stylix
    ./system-packages
    ./users
    ./virtualbox
    ./vpn
    ./workarounds
    ./yubikey
  ];
}
