{
  imports = [
    ./adb
    ./agenix
    ./authentik
    ./basic-packages
    ./bootloader
    ./build-vm
    ./certs
    ./cleanup
    ./cloudflare-warp
    ./desktop
    ./docker
    ./fedifetcher
    ./firmware-update
    ./fonts
    ./gaming
    ./hardware
    ./hetzner
    ./home-manager
    ./latest-kernel
    ./locale
    ./mastodon
    ./matrix
    ./networking-tools
    ./nginx
    ./nix
    ./oci-containers
    ./openssh
    ./optimization
    ./overlays
    ./plasma
    ./postgresql
    ./security
    ./stylix
    ./users
    ./virtualbox
    ./vpn
    ./workarounds
    ./yubikey
    ./zsh
  ];
}
