{
  imports = [
    ./common
    ./modules/neovim
    ./modules/plasma
    ./modules/desktop.nix
    ./modules/dev-tools.nix
    ./modules/system-tools.nix
    ./modules/nix-tools.nix
    ./modules/git.nix
    ./modules/starship.nix
    ./modules/wezterm.nix
    ./modules/shells.nix
    ./modules/ssh.nix
    ./modules/browsers.nix
    ./modules/gaming.nix
    ./modules/keepass.nix
    ./modules/fun.nix
    ./modules/media-player.nix
    ./modules/code-editors.nix
  ];
}
