name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0.3.2
        with:
          endpoint: https://attic.mnzn.dev
          cache: main
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Check flake
        run: nix flake check

      - name: Install tools
        run: nix profile install nixpkgs#direnv nixpkgs#nix-direnv

      - name: Set up direnv
        run: direnv allow

      - name: Colmena build
        run: direnv exec . colmena build --verbose --no-build-on-target
